; For more options you can set here, see /usr/share/doc/gitea/app.ini.example
; For OpenMandriva defaults, see /usr/share/gitea/conf/app.ini
RUN_USER = gitea
RUN_MODE = prod
WORK_PATH = /srv/gitea

[repository]
ROOT = /srv/gitea/repos
PREFERRED_LICENSES = GPL-3.0,AGPL-3.0,LGPL-3.0,GPL-2.0,LGPL-2.1,Apache License 2.0,MIT License

[repository.local]
LOCAL_COPY_PATH = /srv/gitea/local-repo
LOCAL_WIKI_PATH = /srv/gitea/local-wiki

[repository.upload]
TEMP_PATH = /srv/gitea/uploads

[server]
START_SSH_SERVER = true
SSH_PORT = 2222
APP_DATA_PATH = /srv/gitea/data
LFS_START_SERVER = true

[lfs]
PATH = /srv/gitea/data/lfs
LFS_HTTP_AUTH_EXPIRY = 20m

[database]
DB_TYPE = postgres
HOST = /run/postgresql
NAME = gitea
USER = gitea
SSL_MODE = disable
PASSWD = @PG_PASSWORD@

[indexer]
ISSUE_INDEXER_PATH = /srv/gitea/indexers/issues.bleve

[cache]
ADAPTER = redis
HOST = network=unix,addr=/run/redis/gitea/redis.sock,db=0

[session]
PROVIDER = redis
PROVIDER_CONFIG = network=unix,addr=/run/redis/gitea/redis.sock,db=1
COOKIE_SECURE = true

[queue.issue_indexer]
TYPE = redis
CONN_STR = network=unix,addr=/run/redis/gitea/redis.sock,db=2

[queue.mailer]
TYPE = redis
CONN_STR = network=unix,addr=/run/redis/gitea/redis.sock,db=3

[queue.pr_patch_checker]
TYPE = redis
CONN_STR = network=unix,addr=/run/redis/gitea/redis.sock,db=4

[queue.mirror]
TYPE = redis
CONN_STR = network=unix,addr=/run/redis/gitea/redis.sock,db=5

[security]
INSTALL_LOCK = true

[service]
REGISTER_EMAIL_CONFIRM = true
DISABLE_REGISTRATION = false
ENABLE_CAPTCHA = true

[picture]
AVATAR_UPLOAD_PATH = /srv/gitea/data/avatars
REPOSITORY_AVATAR_UPLOAD_PATH = /srv/gitea/data/repo-avatars

[attachment]
PATH = /srv/gitea/data/attachments

[log]
MODE = console
LEVEL = Info
